In [ ]:
import numpy as np

In [ ]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(5,)

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b=np.array({'first':[1,2,3,4,5]})
b

array({'first': [1, 2, 3, 4, 5]}, dtype=object)

In [ ]:
b.shape

()

In [ ]:
b=np.ones((4,4))
b

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
b=np.ones((4,4),dtype='int8')
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
b=np.ones((4,4),dtype='int8',order='F')
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
b=np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [ ]:
b=np.full((4,4),fill_value=10)
b

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [ ]:
b=np.full((3,3),fill_value=5)
b

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
b=np.linspace(0,5,5)
b


array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [ ]:
b=np.linspace(1234,5,5,dtype='int8')
b

array([-46, -98, 107,  56,   5], dtype=int8)

In [ ]:
b=np.linspace(1234,5,5)
b

array([1234.  ,  926.75,  619.5 ,  312.25,    5.  ])

In [ ]:
import time
time.time()

1693580311.9576616

In [ ]:
time.ctime()

'Fri Sep  1 14:59:17 2023'

In [ ]:
b=np.linspace(1234,5,5,dtype=np.int16)
b=np.random.random()
b

0.8456210176167989

In [ ]:
b=np.linspace(25,6,dtype=np.int8)
b=np.random.random()
b

0.08410469134813736